### ISSUE TITLE
Is it possible to support the C raw string literal to make the grammar a little simple to read?

### ISSUE THREAD

**Issue by asmwarrior** [soasme/PeppaPEG#139]
https://www.soasme.com/PeppaPEG/tutcalc.html

When reading the document, I see many C escape code, which makes the grammar a bit hard to read.

It looks like gcc support it. ( see this post: https://stackoverflow.com/questions/24850244/does-c-support-raw-string-literals )

Thanks.

**Comment by soasme** [comment]
@asmwarrior Thanks for coming it up. I think it's a good idea.

Though the library is intended to be also useable on ANSI C environments, I don't see a reason why not use more advanced & modern C features in the documentations.  A quick research shows there is a Sphinx plugin that we can use to show code for both escaped & string literals through tabs. (https://pypi.org/project/sphinx-code-tabs/)

I'll update the documentation when having time.

**Comment by soasme** [comment]
After spending some time on it, I decided not to make any change of it.

As mentioned in the given link, "C (C90, C99, C11) does not support this feature or any other similar feature."
I would prefer not to check in some pieces of code that are bound to a specific build tooling set.

Close the issue.
